FROM --platform=linux/amd64 golang:1.21.1-bullseye@sha256:b6ef23e6d8bd0522fbc17f6fb808f1634e61745e654fa421601506f065b52ff4
LABEL maintainer="Fleet Developers"

RUN apt-get update && apt-get install -y \
	gcc \
	libgtk-3-dev \
	libayatana-appindicator3-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/fleet
RUN mkdir -p /output

WORKDIR /usr/src/fleet

COPY orbit ./orbit
COPY server ./server
COPY ee ./ee
COPY pkg ./pkg
COPY go.mod go.sum ./

CMD /bin/bash
